### ISSUE TITLE
Scaffold Initial Wagtail Project

### ISSUE THREAD

**Issue by brylie** [TechVentures-dev/textbook-companion#2]
Set up the initial Wagtail project structure for the Textbook Companion application.

## Requirements
1. Use the `wagtail start` command to scaffold the project
2. Create the project in the `/app` directory of the repository
3. Use `wagtail start core app` to create the app with a `core/` directory
4. Configure database settings using the `DATABASE_URL` environment variable

## Tasks
1. Navigate to the project repository root
2. Run the Wagtail start command:
   ```
   wagtail start core app
   ```
3. Add `dj-database-url` to the `requirements.txt` file:
   - Open `app/requirements.txt`
   - Add the following line at the end of the file:
     ```
     dj-database-url>=2.0.0,<3.0.0
     ```
4. Run `pip install -r requirements.txt` after saving the file

5. Configure the database settings in app/core/settings/base.py to use the DATABASE_URL environment variable:

Open app/core/settings/base.py
Add the following import at the top of the file:
```python
import dj_database_url

Replace the existing DATABASES configuration with:
pythonCopyDATABASES = {
    'default': dj_database_url.config(
        default='postgres://user:pass@localhost/dbname',
        conn_max_age=600,
        conn_health_checks=True,
    )
}
```

6. Configure the database settings in `app/core/settings/base.py` to use the `DATABASE_URL` environment variable:
   - Open `app/core/settings/base.py`
   - Add the following import at the top of the file:
     ```python
     import dj_database_url
     ```
   - Replace the existing `DATABASES` configuration with:
     ```python
     DATABASES = {
         'default': dj_database_url.config(
             default='postgres://user:pass@localhost/dbname',
             conn_max_age=600,
             conn_health_checks=True,
         )
     }
     ```
Update the docker-compose.yaml file to ensure the DATABASE_URL is properly set for the app service:

Open docker-compose.yaml
In the app service configuration, add an environment section just after the command line:

```yaml
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    network_mode: service:db
```

This DATABASE_URL is constructed as follows:

- postgres://: The protocol for PostgreSQL
- postgres: The username (POSTGRES_USER)
- :postgres: The password (POSTGRES_PASSWORD)
- @db: The hostname (service name for the database in docker-compose)
- :5432: The default PostgreSQL port
- /postgres: The database name (POSTGRES_DB)

## Acceptance Criteria
- [ ] The Wagtail project is successfully scaffolded in the `/app` directory
- [ ] The `app/` directory contains a `core/` subdirectory with settings and core templates
- [ ] `dj-database-url` (version 2.x) is added to `requirements.txt`
- [ ] Database settings in `app/core/settings/base.py` are configured to use the `DATABASE_URL` environment variable
- [ ] The `docker-compose.yaml` file is updated to include the `DATABASE_URL` in the app service configuration
- [ ] The development environment can successfully connect to the database using the configured settings

## Additional Notes
- This task focuses only on scaffolding the initial project and configuring the database connection
- No additional Wagtail configuration or feature development is required for this task
- Ensure all changes are committed to the repository after completion
- After making these changes, run `docker-compose build` to rebuild the app container with the new requirements

## Helpful Resources
- [Wagtail Getting Started](https://docs.wagtail.org/en/stable/getting_started/index.html)
- [dj-database-url Documentation](https://github.com/jazzband/dj-database-url)
