### ISSUE TITLE
Create Articles App with Article and ArticleIndexPage Models

### ISSUE THREAD

**Issue by brylie** [TechVentures-dev/textbook-companion#3]
Continued from #2

Create a new Django app called `articles` within the Wagtail project and implement `Article` and `ArticleIndexPage` models for experimenting with vector embeddings.

## Requirements
1. Create a new Django app named `articles`
2. Implement an `Article` model inheriting from Wagtail's `Page` model
3. Implement an `ArticleIndexPage` model as a single instance model
4. Include appropriate fields and constraints for both models
5. Create necessary templates for displaying articles and the index page
6. Generate and apply migrations

## Tasks
1. Create the new `articles` app:
   ```
   python manage.py startapp articles
   ```

2. Add the `articles` app to `INSTALLED_APPS` in `app/core/settings/base.py`:
   ```python
   INSTALLED_APPS = [
       ...
       'articles',
       ...
   ]
   ```

3. Create the `Article` and `ArticleIndexPage` models in `articles/models.py`:
   ```python
   from django.db import models
   from wagtail.models import Page
   from wagtail.fields import RichTextField
   from wagtail.admin.panels import FieldPanel

   class ArticleIndexPage(Page):
       max_count = 1
       parent_page_types = ['home.HomePage']
       subpage_types = ['Article']

       body = RichTextField(blank=True)

       content_panels = Page.content_panels + [
           FieldPanel('body'),
       ]

       def get_context(self, request):
           context = super().get_context(request)
           context['articles'] = Article.objects.child_of(self).live().order_by('title')
           return context

   class Article(Page):
       parent_page_types = ['ArticleIndexPage']
       subpage_types = []

       body = RichTextField()

       content_panels = Page.content_panels + [
           FieldPanel('body'),
       ]
   ```

4. Create templates for displaying articles and the index page:

   a. Create `articles/templates/articles/article_index_page.html`:
   ```html
   {% extends "base.html" %}
   {% load wagtailcore_tags %}

   {% block content %}
       <h1>{{ page.title }}</h1>
       {{ page.body|richtext }}

       <h2>Articles</h2>
       <ul>
       {% for article in articles %}
           <li><a href="{% pageurl article %}">{{ article.title }}</a></li>
       {% empty %}
           <li>No articles found.</li>
       {% endfor %}
       </ul>
   {% endblock %}
   ```

   b. Create `articles/templates/articles/article.html`:
   ```html
   {% extends "base.html" %}
   {% load wagtailcore_tags %}

   {% block content %}
       <h1>{{ page.title }}</h1>
       {{ page.body|richtext }}
   {% endblock %}
   ```

5. Generate migrations:
   ```
   python manage.py makemigrations
   ```

6. Apply migrations:
   ```
   python manage.py migrate
   ```

## Acceptance Criteria
- [ ] The `articles` app is created and properly added to `INSTALLED_APPS`
- [ ] The `ArticleIndexPage` model is implemented as a single instance model with `title` and `body` fields
- [ ] The `ArticleIndexPage` is constrained to be a child of `home.HomePage`
- [ ] The `Article` model is implemented with `title` (inherited from `Page`) and `body` (RichTextField) fields
- [ ] Articles can only be created under the `ArticleIndexPage`
- [ ] Templates for displaying the article index page and individual articles are created
- [ ] The article index page displays a list of articles sorted alphabetically by title
- [ ] Migrations are generated and can be applied successfully
- [ ] The ArticleIndexPage can be created once under the HomePage in the Wagtail admin interface
- [ ] Articles can be created and edited under the ArticleIndexPage in the Wagtail admin interface
- [ ] The ArticleIndexPage and individual Articles can be viewed on the frontend

## Additional Notes
- Ensure that the `articles` app is placed in the correct directory structure within the Wagtail project
- After completing these tasks, you should be able to create and manage articles through the Wagtail admin interface
- This structure will serve as a foundation for experimenting with vector embeddings in future tasks
- The `max_count = 1` property ensures that only one instance of `ArticleIndexPage` can be created

## Helpful Resources
- [Wagtail Page Models](https://docs.wagtail.org/en/stable/topics/pages.html)
- [Wagtail Model Reference](https://docs.wagtail.org/en/stable/reference/pages/model_reference.html)
- [Wagtail Limiting the number of sub-pages](https://docs.wagtail.org/en/stable/topics/pages.html#limiting-the-number-of-sub-pages)
- [Django QuerySet API](https://docs.djangoproject.com/en/stable/ref/models/querysets/)
